name: "Build Android"
on:
  workflow_dispatch:
    
jobs:
    build-android:
        name: Build Android
        runs-on: ubuntu-latest

        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
          
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v5

            - name: Setup Java
              uses: actions/setup-java@v5
              with:
                distribution: 'oracle'
                java-version: '17'

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: '3.35.4'
                channel: 'stable'

            - name: Install Dependencies
              run: flutter pub get

            - name: Extract version from pubspec.yaml
              run: |
                VERSION=$(grep -E '^version:' pubspec.yaml | awk '{print $2}' | cut -d'+' -f1)
                echo "VERSION=$VERSION" >> $GITHUB_ENV

            - name: Build APK (arm64-v8a)
              run: flutter build apk --release --target-platform android-arm64 --build-number ${{ github.run_number }}

            - name: Rename APK
              run: |
                mv build/app/outputs/flutter-apk/app-release.apk \
                   build/app/outputs/flutter-apk/bloomee_tunes_v${{ env.VERSION }}_arm64-v8a.apk

            - name: Upload Artifact
              uses: actions/upload-artifact@v5
              with:
                name: bloomee-android-v${{ env.VERSION }}
                path: build/app/outputs/flutter-apk/bloomee_tunes_v${{ env.VERSION }}_arm64-v8a.apk
